//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.07 at 04:01:52 PM CET 
//

package io.cryptomage.eidas.verifysignaturewsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the TrustedProfileSignatureVerification.wsdl
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private static final QName _VerificationException_QNAME = new QName("http://verification.zp.epuap.gov.pl",
			"VerificationException");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * TrustedProfileSignatureVerification.wsdl
	 * 
	 */
	public ObjectFactory() {
		/**
		 * Auto generated method
		 */
	}

	/**
	 * Create an instance of {@link VerifySignatureResponse }
	 * 
	 * @return response
	 */
	public VerifySignatureResponse createVerifySignatureResponse() {
		return new VerifySignatureResponse();
	}

	/**
	 * Create an instance of {@link VerifySignature }
	 * 
	 * @return VerifySignature object
	 */
	public VerifySignature createVerifySignature() {
		return new VerifySignature();
	}

	/**
	 * Create an instance of {@link ArrayOfAttachment }
	 * 
	 * @return array of attachment
	 */
	public ArrayOfAttachment createArrayOfAttachment() {
		return new ArrayOfAttachment();
	}

	/**
	 * Create an instance of {@link VerificationException }
	 * 
	 * @return exception
	 */
	public VerificationException createVerificationException() {
		return new VerificationException();
	}

	/**
	 * Create an instance of {@link Attachment }
	 * 
	 * @return attachment
	 */
	public Attachment createAttachment() {
		return new Attachment();
	}

	/**
	 * Create an instance of {@link JAXBElement
	 * }{@code <}{@link VerificationException }{@code >}}
	 * 
	 * @param value
	 * @return JaxBElement
	 */
	@XmlElementDecl(namespace = "http://verification.zp.epuap.gov.pl", name = "VerificationException")
	public JAXBElement<VerificationException> createVerificationException(VerificationException value) {
		return new JAXBElement<>(_VerificationException_QNAME, VerificationException.class, null, value);
	}

}
