//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.07 at 04:01:52 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://verification.zp.epuap.gov.pl")
package io.cryptomage.eidas.verifysignaturewsdl;
