//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.07 at 04:01:52 PM CET 
//

package io.cryptomage.eidas.verifysignaturewsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="doc" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="attachments" type="{http://verification.zp.epuap.gov.pl}ArrayOfAttachment"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "doc", "attachments" })
@XmlRootElement(name = "verifySignature")
public class VerifySignature {

	@XmlElement(required = true)
	protected byte[] doc;
	@XmlElement(required = true, nillable = true)
	protected ArrayOfAttachment attachments;

	/**
	 * Gets the value of the doc property.
	 * 
	 * @return possible object is byte[]
	 */
	public byte[] getDoc() {
		return doc;
	}

	/**
	 * Sets the value of the doc property.
	 * 
	 * @param value
	 *            allowed object is byte[]
	 */
	public void setDoc(byte[] value) {
		this.doc = value;
	}

	/**
	 * Gets the value of the attachments property.
	 * 
	 * @return possible object is {@link ArrayOfAttachment }
	 * 
	 */
	public ArrayOfAttachment getAttachments() {
		return attachments;
	}

	/**
	 * Sets the value of the attachments property.
	 * 
	 * @param value
	 *            allowed object is {@link ArrayOfAttachment }
	 * 
	 */
	public void setAttachments(ArrayOfAttachment value) {
		this.attachments = value;
	}

}
